### ISSUE TITLE
RuntimeWarning at "/opt/splunk/etc/apps/TA-cryptosuite/bin/crypt.py", line 203 : Failed to load AES key and/or IV: Key and/or IV do not have the correct length. Key must be 16, 24 or 32 bytes. IV must be 16 bytes..

### ISSUE THREAD

**Issue by hju2160** [hRun/TA-cryptosuite#5]
i have read a docx, genarate a aes key with iv like this:
c4dc76bff97934e458d193cd25902b0567da99b22eef6f6ed1fd179830b6c6e9
27958ae8b1e7e23e2089c79e39335c4e
Key in line 1 and IV in line 2. Then copy it to key/salt
![image](https://github.com/hRun/TA_cryptosuite/assets/95600382/53d295d0-64f0-4f4d-afb9-925d87ce8d43)
Other config like docx. But when i run command to encrypted fields, it output error bellow:
![image](https://github.com/hRun/TA_cryptosuite/assets/95600382/6fc0060c-9e08-45a0-b463-4f1f38768e22)
Pls, help me!

Thank you so much!

**Comment by hRun** [comment]
fixed in 50906d44e376e4265eeb80e88455dfceaf31b1be

**Comment by hju2160** [comment]
thanks, I will be testing it 💯 
Have a nice works day!

**Comment by hRun** [comment]
@hju2160 took a while, but the new version was finally reviewed and approved for splunk enterprise and cloud. it should become available on splunkbase in the next couple of minutes.
